name = "cquill"
version = "0.1.0"
target = "erlang"

description = "A compile-time safe database library for Gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "justin4957", repo = "cquill" }
links = [{ title = "Documentation", href = "https://hexdocs.pm/cquill" }]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_erlang = ">= 1.0.0 and < 2.0.0"
gleam_otp = ">= 1.0.0 and < 2.0.0"
pog = ">= 4.0.0 and < 5.0.0"
clip = ">= 1.2.0 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"
envoy = ">= 1.1.0 and < 2.0.0"
simplifile = ">= 2.3.2 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
gleescript = ">= 1.5.2 and < 2.0.0"
