name = "cquill"
version = "0.1.0"
target = "erlang"

description = "A compile-time safe database library for Gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "coolbeans", repo = "cquill" }
links = [{ title = "Documentation", href = "https://hexdocs.pm/cquill" }]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
